[package]
name = "hecto"
version = "0.2.0"
authors = ["Philipp Flenker <hello@philippflenker.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.22.1"
unicode-segmentation = "1"
console = "0.15.8"
